services:
  db:
    image: mysql:latest
    container_name: verzelcaixa_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: verzel_db
      MYSQL_USER: Patrick
      MYSQL_PASSWORD: Patrick@1
    ports:
      - "3306:3306"
    volumes:
      - mysqlcaixa_data:/var/lib/mysql
    networks:
      - verzelcaixa_network
    restart: unless-stopped

volumes:
  mysqlcaixa_data:

networks:
  verzelcaixa_network:
    driver: bridge